[settings]
experimental = true
lockfile = true

[tools]
go = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
uv = "latest"

[env]
TF_PLUGIN_CACHE_DIR = "{{ env.HOME }}/.terraform.d/plugin-cache"
XDG_CONFIG_HOME = "{{ env.HOME }}/.config"
